namespace OpenMetaverse.Rendering
{
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     This code was generated by a tool.
    //     Runtime Version:4.0.30319.18444
    //
    //     Changes to this file may cause incorrect behavior and will be lost if
    //     the code is regenerated.
    // </auto-generated>
    //------------------------------------------------------------------------------

    // 
    // This source code was auto-generated by xsd, Version=4.0.30319.1.
    // 

    using System.Xml.Serialization;

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlRoot("linden_skeleton", Namespace = "", IsNullable = false)]
    public partial class LindenSkeleton
    {

        private Joint boneField;

        private float versionField;

        private bool versionFieldSpecified;

        private string num_bonesField;

        private string num_collision_volumesField;

        /// <remarks/>
        public Joint bone
        {
            get
            {
                return this.boneField;
            }
            set
            {
                this.boneField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public float version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool versionSpecified
        {
            get
            {
                return this.versionFieldSpecified;
            }
            set
            {
                this.versionFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttribute(DataType = "positiveInteger")]
        public string num_bones
        {
            get
            {
                return this.num_bonesField;
            }
            set
            {
                this.num_bonesField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute(DataType = "positiveInteger")]
        public string num_collision_volumes
        {
            get
            {
                return this.num_collision_volumesField;
            }
            set
            {
                this.num_collision_volumesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Joint : JointBase
    {

        private CollisionVolume[] collision_volumeField;

        private Joint[] boneField;

        private float[] pivotField;

        /// <remarks/>
        [XmlElement("collision_volume")]
        public CollisionVolume[] collision_volume
        {
            get
            {
                return this.collision_volumeField;
            }
            set
            {
                this.collision_volumeField = value;
            }
        }

        /// <remarks/>
        [XmlElement("bone")]
        public Joint[] bone
        {
            get
            {
                return this.boneField;
            }
            set
            {
                this.boneField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public float[] pivot
        {
            get
            {
                return this.pivotField;
            }
            set
            {
                this.pivotField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CollisionVolume : JointBase
    {
    }

    /// <remarks/>
    [XmlInclude(typeof(Joint))]
    [XmlInclude(typeof(CollisionVolume))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class JointBase
    {

        private string nameField;

        private float[] posField;

        private float[] rotField;

        private float[] scaleField;

        /// <remarks/>
        [XmlAttribute(DataType = "token")]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public float[] pos
        {
            get
            {
                return this.posField;
            }
            set
            {
                this.posField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public float[] rot
        {
            get
            {
                return this.rotField;
            }
            set
            {
                this.rotField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public float[] scale
        {
            get
            {
                return this.scaleField;
            }
            set
            {
                this.scaleField = value;
            }
        }
    }
}
