#pragma once

enum LLTYPES
{
	LLTYPE_U8,
	LLTYPE_U16,
	LLTYPE_U32,
	LLTYPE_U64,
	LLTYPE_S8,
	LLTYPE_S16,
	LLTYPE_S32,
	LLTYPE_S64,
	LLTYPE_F8,
	LLTYPE_F16,
	LLTYPE_F32,
	LLTYPE_F64,
	LLTYPE_LLUUID,
	LLTYPE_BOOL,
	LLTYPE_LLVECTOR3,
	LLTYPE_LLVECTOR3D,
	LLTYPE_QUATERNION,
	LLTYPE_IPADDR,
	LLTYPE_IPPORT,
	LLTYPE_VARIABLE,
	LLTYPE_FIXED,
	LLTYPE_SINGLE,
	LLTYPE_MULTIPLE,
	LLTYPE_NULL
};

extern TCHAR *LLTYPES[];
extern TCHAR *LLKEYWORDS[];
