#!/usr/bin/perl -w

print "--- building libsecondlife-cs\n";

system('cd ../../libsecondlife-cs && ./build')
	and die "*** failed to build libsecondlife-cs\n";

print "--- building Decoder\n";

if (-e 'Decoder.exe' && -M '../../libsecondlife-cs/bin/Debug/libsecondlife.dll' < -M 'Decoder.exe') {
	system('make clean')
		and die "*** make clean failed\n";
}

system('make', @ARGV)
	and die "*** make failed\n";
